# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170204_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateField(),
        ),
    ]
