# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170204_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
