# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170208_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='reply',
        ),
        migrations.AlterField(
            model_name='comment',
            name='event_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Event'),
            preserve_default=False,
        ),
    ]
