# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170209_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Comment'),
            preserve_default=False,
        ),
    ]
